services:

  mongodb:
    image: mongo:7
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    image: manojkumarkv/mean-backend:latest
    container_name: backend
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017/meanapp
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    image: manojkumarkv/mean-frontend:latest
    container_name: frontend
    restart: always
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

volumes:
  mongo_data:

networks:
  app-network:
    driver: bridge
